
export enum RiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  UNKNOWN = 'UNKNOWN',
}

export interface GroundingSource {
  uri: string;
  title: string;
}

export interface AnalysisResult {
  riskLevel: RiskLevel;
  summary: string;
  details: string[];
  sources: GroundingSource[];
  originalContent: string;
  originalType: 'text' | 'url';
}

export interface EducationalItem {
  title: string;
  content: string;
}

export interface ChatMessage {
  role: 'user' | 'model';
  text: string;
}


export const educationalContent: EducationalItem[] = [
  {
    title: "Check the Source",
    content: "Investigate the website, author, and publisher. Are they reputable? Do they have a history of accuracy? Look for an 'About Us' page and contact information. Be wary of unfamiliar sources or those with a clear agenda.",
  },
  {
    title: "Verify Websites and URLs",
    content: "Before trusting a website, check its domain. Does it look professional? Look for a padlock icon in the address bar (HTTPS). Be cautious of URLs that mimic well-known sites but have slight misspellings. Use WHOIS tools to check how long a domain has been registered; newer domains can be a sign of a less established source."
  },
  {
    title: "Look for Evidence and Corroboration",
    content: "Credible stories are backed by evidence, such as quotes from experts, official data, or documents. Check if other reputable news outlets are reporting the same story. A lack of coverage elsewhere can be a major red flag.",
  },
  {
    title: "Beware of Emotional Language",
    content: "Misinformation often uses sensationalist or emotionally charged language to provoke a strong reaction (fear, anger, excitement). Be skeptical of headlines with excessive capitalization, exclamation points, or dramatic claims.",
  },
  {
    title: "Verify Images and Videos",
    content: "Images and videos can be taken out of context, edited, or even generated by AI. Use reverse image search tools (like Google Images) to see where an image originated and if it has been used in other contexts.",
  },
  {
    title: "Identify Author Bias",
    content: "Consider whether the author or publication has a particular bias. Does the story present a balanced view, or does it seem to be pushing a specific agenda? Look for objective language versus opinionated or persuasive wording."
  }
];